### ISSUE TITLE
Obstacle avoidance solely based on kinect ? 

### ISSUE THREAD

**Issue by victorkhoo** [danimtb/pioneer3at_ETSIDI#1]
Hi, I am new to ros system and i hope you could help me. I currently using ros hydro in ubuntu 12.04

i am doing a mini project to use kinect for obstacle avoidance and i look though your navigation stack is mainly based on Laser Sick LMS100 right ? since the navigation is based on amcl ? (Correct me if i am wrong)

I not sure which part of the cpp file tell me the kinect data received for obstacle avoidance. Is it possible to do it just by using a kinect for obstacle avoidance ? 

I do understand using kinect_to_laser.launch use depthimage_to_laserscan help Converts a 3D Point Cloud into a 2D laser scan. This is useful for making devices like the Kinect appear like a laser scanner for 2D-based algorithms. 

So for now, i did the roslaunch pioneer_utils navigation_p3at.launch and get the following error.

[ WARN] [1445956692.807409318]: Waiting on transform from base_link to map to become available before running costmap, tf error: 
[ WARN] [1445956697.853706464]: Waiting on transform from base_link to map to become available before running costmap, tf error: 
[ WARN] [1445956702.898947491]: Waiting on transform from base_link to map to become available before running costmap, tf error: 
[ WARN] [1445956707.945738360]: Waiting on transform from base_link to map to become available before running costmap, tf error: 
[ WARN] [1445956712.990911754]: Waiting on transform from base_link to map to become available before running costmap, tf error: 

Thanks

**Comment by bailiqun** [comment]
what is your tf tree look like? it seem like your transform failed.it should be map->odom(if you have odom data)->base_link->laser(convert by kinect)

**Comment by victorkhoo** [comment]
Thanks Bailiqun for reply. I do a rosrun rqt_graph rqt_graph. I quite new to this, glad you could guide me. 

![rosgraph](https://cloud.githubusercontent.com/assets/15135833/10778645/25bff346-7d63-11e5-8e0d-5e5bfbbceec3.png)

**Comment by bailiqun** [comment]
maybe  this will help .
https://github.com/turtlebot/turtlebot_apps/tree/indigo/turtlebot_navigation
turtlebot also use kinect  to navigation,all launch files pretty clear.

**Comment by danimtb** [comment]
Hi @victorkhoo!
Thanks a lot for your interest in my work!

As you see my navigation stack configuration is based on kinect and Sick LMS11 laser.
Obviously, laser is much better for localization than kinect but you can use just kinect camera to localize and avoid obstacles.

AMCL is used to localize the robot in a map publish by map_server. I've just updated navigation files to support navigation without any map, so it's a good point to start in case you don't want to load any map. 

You should check [local_navigation_p3at.launch](https://github.com/danimtb/pioneer3at_ETSIDI/blob/master/pioneer_utils/navigation/local_navigation/local_navigation_p3at.launch) and just get rid of *sick_lms1xx* from **observation_sources** in both [global_costmap_params.yaml](https://github.com/danimtb/pioneer3at_ETSIDI/blob/master/pioneer_utils/navigation/local_navigation/global_costmap_params.yaml) and [local_costamp_params.yaml](https://github.com/danimtb/pioneer3at_ETSIDI/blob/master/pioneer_utils/navigation/common/local_costmap_params.yaml).

As you have said, I use depthimage_to_laserscan to split the pointclud2 from kinect into 3 different laserscan data. [kinect_to_laser.launch](https://github.com/danimtb/pioneer3at_ETSIDI/blob/master/pioneer_utils/sensors/kinect_to_laser.launch) is the main one.

Kinect node is launched from [pioneer3at-rosaria.launch(]https://github.com/danimtb/pioneer3at_ETSIDI/blob/master/pioneer_utils/sensors/pioneer3at-rosaria.launch)


<include file="$(find freenect_launch)/launch/freenect.launch"/>

and sensor frame *camera_link* is "linked" with a static_transform:

 <node pkg="tf" type="static_transform_publisher" name="base_to_camera_broadcaster" args="-0.020 0 0.360 0 0 0 base_link camera_link 1" />

Those are configurations related to my robot hardware position, so you should proceed in the same way but with your own config.

If you follow [ROS navigation tutorial](http://wiki.ros.org/navigation/Tutorials/RobotSetup) you'll find this information much more understandable.

Hope it helps!!

**Comment by victorkhoo** [comment]
Hi @danimtb ,
Thanks for your detailed guidance and i understand your detailed instruction.  
After trying for few days, I still can't troubleshoot the problem. I still got this warning when i roslaunch local_navigation_p3at.launch
[ WARN] [1445956692.807409318]: Waiting on transform from base_link to map to become available before running costmap, tf error: 

I try to follow ur instruction get rid of sick_lms1xx from observation_sources in both global_costmap_params.yaml and local_costamp_params.yaml. I even remove the following in pioneer3at-rosaria.launch and it still don't work. 

Removed : 
<node pkg="tf" type="static_transform_publisher" name="base_to_laser_broadcaster" args="-0.195 0 0.390 3.141592 0 0 base_link laser 1" />


  <include file="$(find pioneer_utils)/sensors/LMS1xx.launch"/>


  <include file="$(find pioneer_utils)/sensors/laser_filter/scan_filtered.launch"/>

In local_navigation_p3at.launch, i tried playing with it and remove anything related to global_map, 
But one thing for sure is that the map_server node is not launch =) Hope you could continue to help me. Once again thank you !

**Comment by danimtb** [comment]
Hi @victorkhoo,

Local navigation is under revision right now to fix problem you report. You are right, something is missing there.
I'll figure out as soon as possible. Meanwhile you could try with global_navigation.launch to try if everything is working.

**Comment by victorkhoo** [comment]
Hi, any solution to the local navigation ? I still stuck with my project.

**Comment by victorkhoo** [comment]
Hi @danimtb 

any idea why result still the same ?

**Comment by danimtb** [comment]
Hi @victorkhoo

I've done donde checks with mi P3AT robots and local nav is working now. I
havent pushed changes yet, will do it this evening so you can check them.

I'll try to help you with your setup asap!

**Comment by victorkhoo** [comment]
Thank you very much for your patience and guidance. I feeling desperate because I am solo and clueless about this project.

**Comment by danimtb** [comment]
@victorkhoo give some details about your setup so I have a clear idea

are u using a Pioneer 3 AT robot?
do u have more sensors apart from Kinect?
are u running ros in an embedded computer?
which version of ros do u have?

**Comment by victorkhoo** [comment]
Yes, I am using P3AT
only using Kinect
I running ros in my laptop, usb to serial comm work. 
i using ros hydro

**Comment by victorkhoo** [comment]
My guess is some issue with the TF. Probably because your TF setting is set to publish and subscribe laser, kinect, map information. That why the error is shown to be related to "map". By right in local navigation, there should not be map in it. I not too sure where to edit the TF part. Correct me if i am wrong. Thanks

**Comment by danimtb** [comment]
Hi @victorkhoo,
Local navigation (without map) is now working.
The main launchfiles to run local navigation are [pioneer3at-rosaria.launch](https://github.com/danimtb/pioneer3at_ETSIDI/blob/master/pioneer_utils/sensors/pioneer3at-rosaria.launch) and [local_navigation_p3at.launch](https://github.com/danimtb/pioneer3at_ETSIDI/blob/master/pioneer_utils/navigation/local_navigation/local_navigation_p3at.launch).

Remember you should get rid of everything related to laser node LMS1xx and configure your static transformation between base_link and camera_link. Edit this line with the position of the Kinect in your robot:
``node pkg="tf" type="static_transform_publisher" name="base_to_camera_broadcaster" args="-0.020 0 0.360 0 0 0 base_link camera_link 1" />``

You'll have to edit both local and global costmaps to delete configs related to LMS1xx laser node.

I encourage to fork this repository, create your own branch, commit changes with your own modification and push them to your repository so I can have a look and try to help you.

**Comment by victorkhoo** [comment]
Thanks daniel. I will fork ur repository again and update you again. Thank for your help bro.

**Comment by victorkhoo** [comment]
Thanks so much for your help. I rewrote
